[package]
name = "rustsec_comparison"
version = "0.1.0"
edition = "2021"
license = "AGPLv3"
publish = false

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
once_cell = "1.18"
regex = "1.10"
rustsec = "0.28"
strum = "0.25"
strum_macros = "0.25"
tempfile = "3.8"

[workspace]
