[package]
name = "cargo-unmaintained"
version = "0.1.0"
edition = "2021"

[dependencies]
crates-index = { version = "2.2", features = ["git"] }
env_logger = "0.10"
anyhow = { version = "1.0", features = ["backtrace"] }
cargo_metadata = "0.18"
clap = { version = "4.4", features = ["cargo", "derive", "wrap_help"] }
log = "0.4"
once_cell = "1.18"
regex = "1.10"
tempfile = "3.8"

[dev-dependencies]
assert_cmd = "2.0"
ctor = "0.2"
predicates = "3.0"
rayon = "1.8"
snapbox = "0.4"
